# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SC Constructors' Championship
email: rmorrissey@netsuite.com
description: >- # this means to ignore newlines until "baseurl:"
  Just like 'Drive to Survive' - we're back for Season 2.
baseurl: "/scconstructorschampionship" # the subpath of your site, e.g. /blog
url: "https://ryancmorrissey.com" # the base hostname & protocol for your site, e.g. http://example.com
current_fiscal: FY2021
icon: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/198/racing-car_1f3ce.png
github_username:  23maverick23
g_tag: G-1L9JFVQSP5


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - github-pages

sass:
  sass_dir: _scss
  style: compressed

cdn:
  semantic-css: https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css
  semantic-js: https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js
  chart-css: https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.css
  chart-js: https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js
  apex-js: https://cdn.jsdelivr.net/npm/apexcharts@3.19.2/dist/apexcharts.min.js
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - scconstructorschampionship.sublime-project